application: randcphotos-web
version: 1
runtime: python27
api_version: 1
threadsafe: true

handlers:

# re-direct to index.html if no path is give
- url: /
  static_files: static/index.html
  upload: static/index.html

# access the static resources in the root director

- url: /
  static_dir: static/